apiVersion: v1
name: bedrockagent-chart
description: A Helm chart for the ACK service controller for Agents for Amazon Bedrock (Bedrock Agents)
version: 1.4.2
appVersion: 1.4.2
home: https://github.com/aws-controllers-k8s/bedrockagent-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/bedrockagent-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: Bedrock Agents Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/bedrockagent-maintainer
keywords:
  - aws
  - kubernetes
  - bedrockagent
